desc <<-DESC
Updates the versions of the native libraries.

#### Options
* `version`: The version of the native libraries.
* `platform`: The platform to update. Leave blank to update both.

#### Examples
```sh
bundle exec fastlane update_native_libraries version:3.4.0
bundle exec fastlane update_native_libraries version:3.4.0 platform:android
bundle exec fastlane update_native_libraries version:3.4.0 platform:ios
```
DESC
lane :update_native_libraries do |options|
  version = options[:version]
  platform = options[:platform]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  if platform.nil? || platform.downcase == 'android'
    UI.message('Updating native Android libraries.')
    update_native_android_libraries(version)
  end

  if platform.nil? || platform.downcase == 'ios'
    UI.message('Updating native iOS libraries.')
    update_native_ios_libraries(version)
  end
end

desc <<-DESC
Updates Kotlin version of each package.

#### Options
* `version`: The new version for Kotlin.

#### Examples
```sh
bundle exec fastlane update_kotlin_version version:1.7.20
```
DESC
lane :update_kotlin_version do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../packages/cordova-plugin-actito*/plugin.xml']
  regex = /<preference name="GradlePluginKotlinVersion" value=".*" \/>/
  replacement = "<preference name=\"GradlePluginKotlinVersion\" value=\"#{version}\" />"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the version of each package.

#### Options
* `version`: The new version for the libraries.

#### Examples
```sh
bundle exec fastlane bump version:3.4.0
```
DESC
lane :bump do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  # Lerna version
  files = Dir['../lerna.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package version
  files = Dir['../packages/cordova-plugin-actito*/package.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package core dependencies
  files = Dir['../packages/cordova-plugin-actito*/package.json']
  regex = /"cordova-plugin-actito": ".*"/
  replacement = "\"cordova-plugin-actito\": \"#{version}\""
  files.each { |file| update_file(file, regex, replacement) }

  # Plugin
  files = Dir['../packages/cordova-plugin-actito*/plugin.xml']
  regex = /(?<!xml )version=".*"/
  replacement = "version=\"#{version}\""
  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the lockfile of each package and sample app pods.

#### Examples
```sh
bundle exec fastlane update_sample
```
DESC
lane :update_sample do
  lerna_config = JSON.parse(File.read(File.join(__dir__, '..', 'lerna.json')))
  version = lerna_config['version']

  files = Dir['../packages/sample/package.json']
  regex = /"(cordova-plugin-actito.*)": ".*"/
  replacement = "\"\\1\": \"#{version}\""
  files.each { |file| update_file(file, regex, replacement) }

  UI.message('Bootstrapping packages.')
  bootstrap_packages

  UI.message('Recreating platform-specific files.')
  recreate_platform_specific_files
end

desc <<-DESC
Validates and publishes each package.

#### Options
* `dry_run`: Only run in validation mode.

#### Examples
```sh
bundle exec fastlane publish
bundle exec fastlane publish dry_run:true
```
DESC
lane :publish do |options|
  dry_run = options[:dry_run] ||= false

  if dry_run
    directories = Dir["../packages/cordova-plugin-actito*"]

    directories.each do |directory|
      UI.message("Validating '#{directory}' package.")
      stream_shell_command("cd #{directory} && npm publish --dry-run")
    end

    next # skip doing the rest of this lane
  end

  ensure_git_status_clean unless dry_run

  UI.message("Publishing packages.")
  stream_shell_command("lerna publish from-package")
end


def update_file(path, regex, replacement)
  file = File.read(path)
  new_content = file.gsub(regex, replacement)
  File.open(path, 'w') { |line| line.puts new_content }
end

def update_native_android_libraries(version)
  files = Dir['../packages/cordova-plugin-actito*/src/android/build-extras.gradle']
  regex = /def actito_version = '.*'/
  replacement = "def actito_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_libraries(version)
  files = Dir['../packages/cordova-plugin-actito*/plugin.xml']
  regex = /<pod name="Actito\/(Actito.*Kit)" spec=".*" \/>/
  replacement = "<pod name=\"Actito/\\1\" spec=\"#{version}\" />"

  files.each { |file| update_file(file, regex, replacement) }
end

def bootstrap_packages
  stream_shell_command("lerna clean -y")
  stream_shell_command("lerna bootstrap")
end

def recreate_platform_specific_files
  stream_shell_command("cd ../packages/sample && yarn run cordova:refresh-plugins")
end

def stream_shell_command(command)
  success = IO.popen(command) do |io|
    while line = io.gets
      puts line.chomp
    end

    io.close

    $?.success?
  end

  UI.user_error!("Failed to execute shell script '#{command}'") unless success
end
